const dailyUsageResponses = [
  // Временные рамки
  "2-3 hours daily",
  "About 4-5 hours per day",
  "Usually 1-2 hours daily", 
  "Around 3-4 hours each day",
  "Approximately 2 hours per day",
  "About 1-3 hours daily",
  "Usually 2-4 hours per day",
  "Around 1-2 hours each day",
  "Roughly 90 minutes daily",
  "Nearly 3 hours per day",
  "Close to 2 hours each day",
  "Less than 2 hours daily",
  "More than 1 hour per day",
  "Between 1-4 hours daily",
  "Up to 3 hours each day",
  "About 45 minutes to 2 hours daily",
  "Typically 2.5 hours per day",
  "Usually around 80-120 minutes daily",
  "Approximately 1.5-3 hours each day",
  "Normally 2-3.5 hours per day",

  // Активности и цели
  "Messaging family and close friends",
  "Work communication and personal chats",
  "Staying in touch with relatives abroad", 
  "Coordinating with colleagues and friends",
  "Communication with family members",
  "Personal and business conversations",
  "Chatting with friends and coworkers",
  "Keeping contact with close people",
  "Regular communication with loved ones",
  "Professional discussions and casual talks",
  "Family conversations and work coordination",
  "Social interactions with friends",
  "Business communication and personal updates",
  "Daily check-ins with important contacts",
  "Coordinating plans and sharing news",
  "Maintaining relationships with friends and family",
  "Work-related discussions and personal chats",
  "Staying connected with distant relatives",
  "Regular updates with close contacts",
  "Communication for work and social purposes",

  // Паттерны использования
  "Morning messages and evening calls",
  "Throughout the day for work coordination",
  "Mostly evenings and weekends",
  "During breaks and after work hours",
  "Between meetings and in free time",
  "Regular communication during daytime",
  "Mainly evening conversations",
  "Periodic messaging throughout day",
  "Early morning check-ins and night chats",
  "Lunch break conversations and evening updates",
  "Weekend discussions and weekday coordination",
  "After work socializing and morning planning",
  "Scheduled calls and spontaneous messages",
  "Brief interactions during busy periods",
  "Detailed conversations when time permits",
  "Quick updates during work and longer chats after",
  "Formal communications during business hours",
  "Casual exchanges in the evenings",
  "Structured coordination and relaxed chatting",
  "Professional discussions and personal catch-ups",

  // Смешанные и детальные
  "Daily communication with family and colleagues",
  "Regular messaging for work and personal matters",
  "Staying connected with important contacts throughout day",
  "Coordinating daily activities and socializing with friends",
  "Business communication mixed with personal conversations",
  "Family conversations during evenings and work chat during day",
  "Consistent contact with relatives and professional network",
  "Balanced usage for personal relationships and work needs",
  "Frequent communication with close circle of contacts",
  "Regular interaction with family, friends and colleagues",
  "Steady communication flow for various life aspects",
  "Purposeful messaging for coordination and relationship maintenance",
  "Essential daily communication for work and personal life",
  "Moderate usage focused on meaningful conversations",
  "Selective communication with important people in my life",
  "Efficient messaging for necessary coordination and social connection",
  "Practical usage for staying informed and connected",
  "Meaningful exchanges with people who matter most",
  "Focused communication for work productivity and relationship building",
  "Strategic usage for maintaining important personal and professional connections",

  // Дополнительные варианты
  "Voice messages and text conversations daily",
  "Photo sharing and casual chatting regularly",
  "Document exchanges and informal discussions",
  "Group conversations and private messaging",
  "Video calls combined with text communication", 
  "File sharing and coordination messages",
  "News updates and personal conversations",
  "Project discussions and social interactions",
  "Appointment scheduling and friendly chats",
  "Information sharing and relationship maintenance",
  "Work updates and family communication",
  "Social coordination and professional networking",
  "Event planning and casual conversations",
  "Problem solving discussions and social support",
  "Knowledge sharing and emotional connection",
  "Task coordination and personal bonding",
  "Status updates and meaningful dialogue",
  "Quick confirmations and deep conversations",
  "Routine check-ins and special occasion messages",
  "Emergency communications and daily social interaction",

  // Еще больше вариаций
  "Communication spanning different time zones with family",
  "Regular contact maintenance with international friends",
  "Daily coordination with local and remote colleagues", 
  "Consistent messaging with university friends and classmates",
  "Ongoing conversations with neighbors and community members",
  "Active participation in family and friend group chats",
  "Regular updates with former colleagues and mentors",
  "Frequent exchanges with service providers and local businesses",
  "Daily communication with sports teammates and hobby groups",
  "Consistent contact with church members and volunteer organizations",
  "Regular messaging with study groups and professional associations",
  "Active communication with travel companions and adventure buddies",
  "Frequent contact with pet care providers and veterinarians",
  "Daily exchanges with fitness instructors and health professionals",
  "Regular communication with landlords and property managers",
  "Consistent messaging with financial advisors and insurance agents",
  "Frequent contact with childcare providers and school staff",
  "Active communication with elderly family members needing support",
  "Regular updates with medical professionals and therapy providers",
  "Daily coordination with transportation services and delivery personnel",

  // Специфичные сценарии
  "Morning weather updates and evening recap conversations",
  "Lunch menu coordination and dinner planning discussions",
  "Traffic updates and commute coordination messages",
  "Shopping list sharing and price comparison chats",
  "Recipe exchanges and cooking tip discussions",
  "TV show recommendations and movie planning conversations",
  "Book recommendations and reading progress updates",
  "Exercise motivation and fitness progress sharing",
  "Travel planning and destination research discussions",
  "Home improvement coordination and DIY advice sharing",
  "Garden updates and seasonal activity planning",
  "Pet care coordination and animal health discussions",
  "Child development updates and parenting advice exchanges",
  "Career advice discussions and job search coordination",
  "Investment discussions and financial planning conversations",
  "Health updates and medical appointment coordination",
  "Birthday planning and gift coordination messages",
  "Holiday preparation and tradition sharing discussions",
  "Celebration planning and memory sharing conversations",
  "Problem solving and emotional support communications"
];

const randomElement = <T>(arr: T[]): T =>
  arr[Math.floor(Math.random() * arr.length)];

export const generateDailyUsage = (): string => {
  const sentence1 = randomElement(dailyUsageResponses);
  const sentence2 = randomElement(dailyUsageResponses);
  const sentence3 = randomElement(dailyUsageResponses);
  
  return `${sentence1}. ${sentence2}. ${sentence3}.`;
};