const russianNames = {
  // Мужские имена
  anatoliy: 'Анатолий',
  anton: 'Антон',
  arkadiy: 'Аркадий',
  artur: 'Артур',
  boris: 'Борис',
  vadim: 'Вадим',
  valentin: 'Валентин',
  valeriy: 'Валерий',
  viktor: 'Виктор',
  vitaliy: 'Виталий',
  vladimir: 'Владимир',
  vladislav: 'Владислав',
  gennadiy: 'Геннадий',
  georgiy: 'Георгий',
  denis: 'Денис',
  dmitriy: 'Дмитрий',
  egor: 'Егор',
  ivan: 'Иван',
  igor: 'Игорь',
  ilya: 'Илья',
  kirill: 'Кирилл',
  konstantin: 'Константин',
  leonid: 'Леонид',
  maksim: 'Максим',
  mikhail: 'Михаил',
  nikita: 'Никита',
  nikolai: 'Николай',
  oleg: 'Олег',
  pavel: 'Павел',
  roman: 'Роман',
  ruslan: 'Руслан',
  sergey: 'Сергей',
  stepan: 'Степан',
  timofey: 'Тимофей',
  fedor: 'Федор',
  aleksandr: 'Александр',
  alexander: 'Александр',
  aleksey: 'Алексей',
  alexey: 'Алексей',
  alex: 'Алекс',
  anatoly: 'Анатолий',
  andrey: 'Андрей',
  andrew: 'Андрей',
  arkady: 'Аркадий',
  artem: 'Артем',
  arthur: 'Артур',
  valera: 'Валера',
  vasily: 'Василий',
  vasiliy: 'Василий',
  victor: 'Виктор',
  vitaly: 'Виталий',
  gennady: 'Геннадий',
  georgy: 'Георгий',
  george: 'Георгий',
  gleb: 'Глеб',
  grigory: 'Григорий',
  grigoriy: 'Григорий',
  grisha: 'Гриша',
  daniil: 'Даниил',
  danila: 'Данила',
  dmitry: 'Дмитрий',
  dima: 'Дима',
  zakhar: 'Захар',
  matvey: 'Матвей',
  nikolay: 'Николай',
  petr: 'Петр',
  stanislav: 'Станислав',
  timur: 'Тимур',
  yaroslav: 'Ярослав',

  // Женские имена
  albina: 'Альбина',
  alisa: 'Алиса',
  alla: 'Алла',
  anastasia: 'Анастасия',
  anfisa: 'Анфиса',
  anna: 'Анна',
  arina: 'Арина',
  daria: 'Дарья',
  darina: 'Дарина',
  ekaterina: 'Екатерина',
  elena: 'Елена',
  evgenia: 'Евгения',
  galina: 'Галина',
  inna: 'Инна',
  irina: 'Ирина',
  kira: 'Кира',
  liza: 'Лиза',
  lubov: 'Любовь',
  margarita: 'Маргарита',
  maria: 'Мария',
  marina: 'Марина',
  mira: 'Мира',
  nina: 'Нина',
  olga: 'Ольга',
  polina: 'Полина',
  raisa: 'Райса',
  rita: 'Рита',
  sofia: 'София',
  svetlana: 'Светлана',
  tatiana: 'Татьяна',
  valeria: 'Валерия',
  vera: 'Вера',
  yana: 'Яна',
  yulia: 'Юлия',
};

const firstNamesMale = [
    'Anton',
    'Artur',
    'Boris',
    'Vadim',
    'Valeriy',
    'Viktor',
    'Vitaliy',
    'Vladimir',
    'Georgiy',
    'Denis',
    'Dmitriy',
    'Egor',
    'Ivan',
    'Igor',
    'Ilya',
    'Kirill',
    'Leonid',
    'Maksim',
    'Mikhail',
    'Nikolai',
    'Oleg',
    'Pavel',
    'Roman',
    'Ruslan',
    'Sergey',
    'Stepan',
    'Timofey',
    'Fedor',
    'Aleksey',
    'Alexey',
    'Andrew',
    'Artem',
    'Arthur',
    'Victor',
    'Vitaly',
    'Gennady',
    'Grigory',
    'Dmitry',
    'Matvey',
    'Nikolay',
    'Petr',
  ];
  
  const firstNamesFemale = [
    'Albina',
    'Alisa',
    'Alla',
    'Anastasia',
    'Anfisa',
    'Anna',
    'Arina',
    'Daria',
    'Darina',
    'Ekaterina',
    'Elena',
    'Evgenia',
    'Galina',
    'Inna',
    'Irina',
    'Kira',
    'Liza',
    'Lubov',
    'Margarita',
    'Maria',
    'Marina',
    'Mira',
    'Nina',
    'Olga',
    'Polina',
    'Raisa',
    'Rita',
    'Sofia',
    'Svetlana',
    'Tatiana',
    'Valeria',
    'Vera',
    'Yana',
    'Yulia',
  ];

function checkNames() {
  const missing = [];
  const allNames = firstNamesMale.concat(firstNamesFemale);
  allNames.forEach((name) => {
    // Переводим имя в нижний регистр, чтобы сопоставить с ключами объекта
    if (!russianNames[name.toLowerCase()]) {
      missing.push(name);
    }
  });
  if (missing.length > 0) {
    console.log('Отсутствуют следующие имена в объекте russianNames:', missing);
  } else {
    console.log('Все имена присутствуют в объекте russianNames!');
  }
}

// Запуск функции проверки
checkNames();
