import {
  uniqueNamesGenerator,
  Config,
  colors,
  adjectives,
} from "unique-names-generator";

const firstNames = [
  "Anatoliy",
  "Anton",
  "Arkadiy",
  "Artur",
  "Boris",
  "Vadim",
  "Valentin",
  "Valeriy",
  "Viktor",
  "Vitaliy",
  "Vladimir",
  "Vladislav",
  "Gennadiy",
  "Georgiy",
  "Denis",
  "Dmitriy",
  "Egor",
  "Ivan",
  "Igor",
  "Ilya",
  "Kirill",
  "Konstantin",
  "Leonid",
  "Maksim",
  "Mikhail",
  "Nikita",
  "Nikolai",
  "Oleg",
  "Pavel",
  "Roman",
  "Ruslan",
  "Sergey",
  "Stepan",
  "Timofey",
  "Fedor",
  "Aleksandr",
  "Alexander",
  "Aleksey",
  "Alexey",
  "Alex",
  "Anatoly",
  "Andrey",
  "Andrew",
  "Arkady",
  "Artem",
  "Arthur",
  "Valera",
  "Vasily",
  "Vasiliy",
  "Victor",
  "Vitaly",
  "Gennady",
  "Georgy",
  "George",
  "Gleb",
  "Grigory",
  "Grigoriy",
  "Grisha",
  "Daniil",
  "Danila",
  "Dmitry",
  "Dima",
  "Zakhar",
  "Matvey",
  "Nikolay",
  "Petr",
  "Stanislav",
  "Timur",
  "Yaroslav",
];

const lastNames = [
  "Abramov",
  "Afanasyev",
  "Agapov",
  "Ageyev",
  "Alekseev",
  "Andreev",
  "Anisimov",
  "Antonov",
  "Artamonov",
  "Babkin",
  "Balandin",
  "Baranov",
  "Belov",
  "Bogdanov",
  "Borisov",
  "Bukin",
  "Bulanov",
  "Chernov",
  "Chirkov",
  "Chugunov",
  "Demidov",
  "Denisov",
  "Dorofeev",
  "Dubrovin",
  "Efimov",
  "Egorov",
  "Ermakov",
  "Erokhin",
  "Eroshkin",
  "Evdokimov",
  "Fedorov",
  "Filatov",
  "Frolov",
  "Galitsyn",
  "Gavrilov",
  "Glazunov",
  "Golubev",
  "Goncharov",
  "Gorbachev",
  "Gorbunov",
  "Gorshkov",
  "Grigoriev",
  "Grishin",
  "Gromov",
  "Ignatov",
  "Ilin",
  "Ivanov",
  "Kalinin",
  "Karpov",
  "Kashirin",
  "Kazantsev",
  "Kazmin",
  "Kharitonov",
  "Khokhlov",
  "Kiselev",
  "Kolesnikov",
  "Kondratiev",
  "Konstantinov",
  "Konovalov",
  "Korneev",
  "Korneyev",
  "Korolev",
  "Kostin",
  "Kozlov",
  "Kravchenko",
  "Kuzmin",
  "Kuznetsov",
  "Lapshin",
  "Larionov",
  "Lazarev",
  "Lebedev",
  "Likhachev",
  "Lobanov",
  "Loginov",
  "Makarov",
  "Maksimov",
  "Malakhov",
  "Malyutin",
  "Markov",
  "Martynov",
  "Medvedev",
  "Melnikov",
  "Mironov",
  "Mishin",
  "Morozov",
  "Mozharov",
  "Naumov",
  "Nechayev",
  "Nesterov",
  "Nikitin",
  "Nikolaev",
  "Novikov",
  "Orlov",
  "Osipov",
  "Ovchinnikov",
  "Pakhomov",
  "Panfilov",
  "Pavlov",
  "Petrov",
  "Ponomarev",
  "Popov",
  "Potapov",
  "Prokhorov",
  "Puchkov",
  "Romanov",
  "Rostov",
  "Rudakov",
  "Rusanov",
  "Samoylov",
  "Savin",
  "Semenov",
  "Serov",
  "Shapovalov",
  "Shevchenko",
  "Shevchuk",
  "Shirokov",
  "Shishkin",
  "Shubin",
  "Shumilov",
  "Sidorenko",
  "Sidorov",
  "Simonov",
  "Sinitsyn",
  "Skvortsov",
  "Smirnov",
  "Sobolev",
  "Sokolov",
  "Soloviev",
  "Sorokin",
  "Stepanov",
  "Streltsov",
  "Suvorov",
  "Sysoev",
  "Tarasov",
  "Terekhov",
  "Timofeev",
  "Tkachev",
  "Tomilov",
  "Trifonov",
  "Trofimov",
  "Tsyganov",
  "Tikhonov",
  "Ustinov",
  "Vasilyev",
  "Vikhrov",
  "Vinogradov",
  "Vlasov",
  "Volkov",
  "Voronin",
  "Vorontsov",
  "Vasiliev",
  "Yudin",
  "Zakharov",
  "Zaitsev",
  "Zaytsev",
  "Zhdanov",
  "Zhukov",
  "Ziminov",
  "Zubarev",
  "Zubkov",
  "Zyuzin",
  "Zubanov",
];

export const generateUser = () => {
  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];

  const dictionaries = [adjectives, [firstName, lastName], colors];
  const randomDictionaries = [];

  for (let i = 0; i < 2; i++) {
    const index = Math.floor(Math.random() * dictionaries.length);
    randomDictionaries.push(dictionaries.splice(index, 1)[0]);
  }

  function randomSeparator() {
    const separators = ["_", ""];
    const index = Math.floor(Math.random() * separators.length);
    return separators[index];
  }

  const dictionariesType: Config = {
    dictionaries: [...randomDictionaries],
    length: 2,
    separator: randomSeparator(),
    style: "lowerCase",
  };

  const randomUsername = uniqueNamesGenerator(dictionariesType);
  return { firstName, lastName, username: randomUsername };
};
