const russianNames = {
  anatoliy: 'Анатолий',
  anton: 'Антон',
  arkadiy: 'Аркадий',
  artur: 'Артур',
  boris: 'Борис',
  vadim: 'Вадим',
  valentin: 'Валентин',
  valeriy: 'Валерий',
  viktor: 'Виктор',
  vitaliy: 'Виталий',
  vladimir: 'Владимир',
  vladislav: 'Владислав',
  gennadiy: 'Геннадий',
  georgiy: 'Георгий',
  denis: 'Денис',
  dmitriy: 'Дмитрий',
  egor: 'Егор',
  ivan: 'Иван',
  igor: 'Игорь',
  ilya: 'Илья',
  kirill: 'Кирилл',
  konstantin: 'Константин',
  leonid: 'Леонид',
  maksim: 'Максим',
  mikhail: 'Михаил',
  nikita: 'Никита',
  nikolai: 'Николай',
  oleg: 'Олег',
  pavel: 'Павел',
  roman: 'Роман',
  ruslan: 'Руслан',
  sergey: 'Сергей',
  stepan: 'Степан',
  timofey: 'Тимофей',
  fedor: 'Федор',
  aleksandr: 'Александр',
  alexander: 'Александр',
  aleksey: 'Алексей',
  alexey: 'Алексей',
  alex: 'Алекс',
  anatoly: 'Анатолий',
  andrey: 'Андрей',
  andrew: 'Андрей',
  arkady: 'Аркадий',
  artem: 'Артем',
  arthur: 'Артур',
  valera: 'Валера',
  vasily: 'Василий',
  vasiliy: 'Василий',
  victor: 'Виктор',
  vitaly: 'Виталий',
  gennady: 'Геннадий',
  georgy: 'Георгий',
  george: 'Георгий',
  gleb: 'Глеб',
  grigory: 'Григорий',
  grigoriy: 'Григорий',
  grisha: 'Гриша',
  daniil: 'Даниил',
  danila: 'Данила',
  dmitry: 'Дмитрий',
  dima: 'Дима',
  zakhar: 'Захар',
  matvey: 'Матвей',
  nikolay: 'Николай',
  petr: 'Петр',
  stanislav: 'Станислав',
  timur: 'Тимур',
  yaroslav: 'Ярослав',
};

export const converterName = (aiName: string) => {
  const lowerCaseName = aiName
    .toLowerCase()
    .replace('.', '')
    .trim() as keyof typeof russianNames;
  return russianNames[lowerCaseName] || aiName;
};
