import {
  adjectives,
  colors,
  Config,
  uniqueNamesGenerator,
} from 'unique-names-generator';

const firstNamesMale = [
  'Anton',
  'Artur',
  'Boris',
  'Vadim',
  'Valeriy',
  'Viktor',
  'Vitaliy',
  'Vladimir',
  'Georgiy',
  'Denis',
  'Dmitriy',
  'Egor',
  'Ivan',
  'Igor',
  'Ilya',
  'Kirill',
  'Leonid',
  'Maksim',
  'Mikhail',
  'Nikolai',
  'Oleg',
  'Pavel',
  'Roman',
  'Ruslan',
  'Sergey',
  'Stepan',
  'Timofey',
  'Fedor',
  'Aleksey',
  'Alexey',
  'Andrew',
  'Artem',
  'Arthur',
  'Victor',
  'Vitaly',
  'Gennady',
  'Grigory',
  'Dmitry',
  'Matvey',
  'Nikolay',
  'Petr',
];

const firstNamesFemale = [
  'Albina',
  'Alisa',
  'Alla',
  'Anastasia',
  'Anfisa',
  'Anna',
  'Arina',
  'Daria',
  'Darina',
  'Ekaterina',
  'Elena',
  'Evgenia',
  'Galina',
  'Inna',
  'Irina',
  'Kira',
  'Liza',
  'Lubov',
  'Margarita',
  'Maria',
  'Marina',
  'Mira',
  'Nina',
  'Olga',
  'Polina',
  'Raisa',
  'Rita',
  'Sofia',
  'Svetlana',
  'Tatiana',
  'Valeria',
  'Vera',
  'Yana',
  'Yulia',
];

const lastNamesMale = [
  'Abramov',
  'Agapov',
  'Alekseev',
  'Andreev',
  'Anisimov',
  'Antonov',
  'Baranov',
  'Belov',
  'Bogdanov',
  'Borisov',
  'Bukin',
  'Bulanov',
  'Chernov',
  'Chirkov',
  'Chugunov',
  'Demidov',
  'Denisov',
  'Dorofeev',
  'Dubrovin',
  'Efimov',
  'Egorov',
  'Ermakov',
  'Erokhin',
  'Eroshkin',
  'Fedorov',
  'Filatov',
  'Frolov',
  'Galitsyn',
  'Gavrilov',
  'Glazunov',
  'Golubev',
  'Gorbunov',
  'Gorshkov',
  'Grishin',
  'Gromov',
  'Ignatov',
  'Ilin',
  'Ivanov',
  'Kalinin',
  'Karpov',
  'Kashirin',
  'Kazmin',
  'Khokhlov',
  'Kiselev',
  'Korneev',
  'Korneyev',
  'Korolev',
  'Kostin',
  'Kozlov',
  'Kuzmin',
  'Lapshin',
  'Larionov',
  'Lazarev',
  'Lebedev',
  'Lobanov',
  'Loginov',
  'Makarov',
  'Maksimov',
  'Malakhov',
  'Malyutin',
  'Markov',
  'Martynov',
  'Medvedev',
  'Melnikov',
  'Mironov',
  'Mishin',
  'Morozov',
  'Mozharov',
  'Naumov',
  'Nechayev',
  'Nesterov',
  'Nikitin',
  'Nikolaev',
  'Novikov',
  'Orlov',
  'Osipov',
  'Pakhomov',
  'Panfilov',
  'Pavlov',
  'Petrov',
  'Popov',
  'Potapov',
  'Puchkov',
  'Romanov',
  'Rostov',
  'Rudakov',
  'Rusanov',
  'Samoylov',
  'Savin',
  'Semenov',
  'Serov',
  'Shevchuk',
  'Shirokov',
  'Shishkin',
  'Shubin',
  'Shumilov',
  'Sidorov',
  'Simonov',
  'Sinitsyn',
  'Smirnov',
  'Sobolev',
  'Sokolov',
  'Soloviev',
  'Sorokin',
  'Stepanov',
  'Suvorov',
  'Sysoev',
  'Tarasov',
  'Terekhov',
  'Timofeev',
  'Tkachev',
  'Tomilov',
  'Trifonov',
  'Trofimov',
  'Tsyganov',
  'Tikhonov',
  'Ustinov',
  'Vasilyev',
  'Vikhrov',
  'Vlasov',
  'Volkov',
  'Voronin',
  'Zakharov',
  'Zaitsev',
  'Zaytsev',
  'Zhdanov',
  'Zhukov',
  'Ziminov',
  'Zubarev',
  'Zubkov',
  'Zyuzin',
  'Zubanov',
];

const lastNamesFemale = [
  'Abramova',
  'Agapova',
  'Alekseeva',
  'Andreeva',
  'Anisimova',
  'Antonova',
  'Baranova',
  'Belova',
  'Bogdanova',
  'Borisova',
  'Bukina',
  'Bulanova',
  'Chernova',
  'Chirkova',
  'Chugunova',
  'Demidova',
  'Denisova',
  'Dorofeeva',
  'Dubrovina',
  'Efimova',
  'Egorova',
  'Ermakova',
  'Erokhina',
  'Eroshkina',
  'Fedorova',
  'Filatova',
  'Frolova',
  'Galitsyna',
  'Gavrilova',
  'Glazunova',
  'Golubeva',
  'Gorbunova',
  'Gorshkova',
  'Grishina',
  'Gromova',
  'Ignatova',
  'Ilyina',
  'Ivanova',
  'Kalinina',
  'Karpova',
  'Kashirina',
  'Kazmina',
  'Khokhlova',
  'Kiseleva',
  'Korneeva',
  'Korneyeva',
  'Koroleva',
  'Kostina',
  'Kozlova',
  'Kuzmina',
  'Lapshina',
  'Larionova',
  'Lazareva',
  'Lebedeva',
  'Lobanova',
  'Loginova',
  'Makarova',
  'Maksimova',
  'Malakhova',
  'Malyutina',
  'Markova',
  'Martynova',
  'Medvedeva',
  'Melnikova',
  'Mironova',
  'Mishina',
  'Morozova',
  'Mozharova',
  'Naumova',
  'Nechayeva',
  'Nesterova',
  'Nikitina',
  'Nikolaeva',
  'Novikova',
  'Orlova',
  'Osipova',
  'Pakhomova',
  'Panfilova',
  'Pavlova',
  'Petrova',
  'Popova',
  'Potapova',
  'Puchkova',
  'Romanova',
  'Rostova',
  'Rudakova',
  'Rusanova',
  'Samoylova',
  'Savina',
  'Semenova',
  'Serova',
  'Shevchukova',
  'Shirokova',
  'Shishkina',
  'Shubina',
  'Shumilova',
  'Sidorova',
  'Simonova',
  'Sinitsyna',
  'Smirnova',
  'Soboleva',
  'Sokolova',
  'Solovieva',
  'Sorokina',
  'Stepanova',
  'Suvorova',
  'Sysoeva',
  'Tarasova',
  'Terekhova',
  'Timofeeva',
  'Tkacheva',
  'Tomilova',
  'Trifonova',
  'Trofimova',
  'Tsyganova',
  'Tikhonova',
  'Ustinova',
  'Vasilyeva',
  'Vikhrova',
  'Vlasova',
  'Volkova',
  'Voronina',
  'Zakharova',
  'Zaitseva',
  'Zaytseva',
  'Zhdanova',
];

export const generateUser = (gender: 'male' | 'female') => {
  const firstNames = gender === 'male' ? firstNamesMale : firstNamesFemale;
  const lastNames = gender === 'male' ? lastNamesMale : lastNamesFemale;

  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];

  const dictionaries = [[lastName], [...adjectives, ...colors]];

  function randomSeparator() {
    const separators = ['_'];
    const index = Math.floor(Math.random() * separators.length);
    return separators[index];
  }

  const dictionariesType: Config = {
    dictionaries: [...dictionaries],
    length: 2,
    separator: randomSeparator(),
    style: 'lowerCase',
  };
  const dictionariesTypeSecond: Config = {
    dictionaries: [
      [`${lastName}${firstName}`],
      Array.from(Array(100 + 1).keys())
        .slice(1)
        .map(String),
    ],
    length: 2,
    separator: randomSeparator(),
    style: 'lowerCase',
  };

  const randomUsername = uniqueNamesGenerator(dictionariesType);
  const randomElseUsername = uniqueNamesGenerator(dictionariesTypeSecond);

  return { firstName, lastName, username: randomUsername, randomElseUsername };
};
